import React from 'react';
import {responsiveHeight, responsiveWidth} from '../utils/Responsive';
import {StyleSheet} from 'react-native';
import * as Colors from '../utils/Colors';
const styles = StyleSheet.create({
  Parent: {
    height: responsiveHeight(100),
    backgroundColor: Colors.TASK_REVIEW_SCREEN_BACKGROUND,
  },
  Header: {
    flexDirection: 'row',
    // borderWidth: 5,
    height: responsiveHeight(12),
    alignItems: 'center',
    paddingLeft: 10,
    justifyContent: 'space-between',
  },
  Image: {
    height: 50,
    width: 50,
    borderRadius: 30,
    marginRight: 40,
  },
  Salutation: {
    // borderWidth: 5,
    height: responsiveHeight(14),
    justifyContent: 'center',
    paddingLeft: 34,
  },
  Name: {
    fontSize: 32,
    fontWeight: 'bold',
    color: Colors.WHITE,
  },
  TextNoOfTasksPending: {
    fontSize: 20,
    color: Colors.WHITE,
  },
  MobileAppDesign: {
    marginTop: 5,
    marginLeft: 25,
    borderWidth: 1,
    height: responsiveHeight(15),
    width: responsiveWidth(85),
    borderColor: Colors.A_DIFFERENT_BLUE,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: Colors.A_DIFFERENT_BLUE,
    shadowColor: Colors.A_DIFFERENT_BLUE,
    elevation: 10,
  },
  TextMobileAppDesign: {
    color: Colors.WHITE,
    fontWeight: 'bold',
    marginTop: 8,
    marginLeft: 20,
    fontSize: 18,
  },
  TextTwoNames: {
    // marginTop: 10,
    color: Colors.WHITE,
    marginLeft: 20,
  },
  ImageBetween1: {
    height: 40,
    width: 40,
    borderRadius: 30,
    marginLeft: 30,
    marginTop: 10,
    position: 'absolute',
  },
  ImageBetween2: {
    height: 40,
    width: 40,
    borderRadius: 30,
    // marginLeft: 20,
    // marginRight: 10,
    marginTop: 10,
    // position: 'absolute',
  },
  TextNow: {
    color: Colors.WHITE,
    margin: 20,
    bottom: 15,
  },
  MiddlePart: {
    // borderWidth: 5,
    paddingTop: 20,
    height: responsiveHeight(13),
    width: responsiveWidth(85),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  TextMonthlyReview: {
    marginTop: 10,
    color: Colors.WHITE,
    fontSize: 25,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  IconParent: {
    margin: 10,
    borderRadius: 80,
    // borderWidth: 5,
    height: 40,
    width: 40,
    backgroundColor: Colors.AQUA,
  },
  Icon: {
    marginLeft: 5,
    marginTop: 5,
  },
  EndPart: {
    paddingTop: 5,
    flexDirection: 'row',
    // borderWidth: 5,
    height: responsiveHeight(39),
    width: responsiveWidth(90),
    // justifyContent: 'space-between',
  },
  EndPartColumnChild1: {
    // borderWidth: 5,
    width: responsiveWidth(40),
    height: responsiveHeight(32),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  TaskDoneParent: {
    backgroundColor: Colors.A_DIFFERENT_BLUE,
    paddingLeft: 60,
    paddingTop: 1,
    borderWidth: 1,
    width: responsiveWidth(37),
    height: responsiveHeight(18),
    borderColor: Colors.A_DIFFERENT_BLUE,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopRightRadius: 20,
  },
  TextNoOfTasksDone: {
    marginTop: 20,
    color: Colors.WHITE,
    fontWeight: 'bold',
    fontSize: 30,
  },
  TextDone: {
    marginTop: 10,
    color: Colors.WHITE,
  },
  TaskOngoingParent: {
    backgroundColor: Colors.A_DIFFERENT_BLUE,
    borderWidth: 1,
    paddingLeft: 50,
    marginTop: 20,
    width: responsiveWidth(37),
    height: responsiveHeight(14),
    borderColor: Colors.A_DIFFERENT_BLUE,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopRightRadius: 20,
  },
  TextOngoing: {
    marginTop: 8,
    color: Colors.WHITE,
  },
  TextNoOfTasksOngoing: {
    margin: 8,
    marginTop: 10,
    color: Colors.WHITE,
    fontWeight: 'bold',
    fontSize: 30,
  },
  EndPartColumnChild2: {
    justifyContent: 'space-between',
    // borderWidth: 5,
    paddingLeft: 13,
    width: responsiveWidth(40),
    height: responsiveHeight(32),
  },
  TaskInProgressParent: {
    backgroundColor: Colors.A_DIFFERENT_BLUE,
    paddingLeft: 50,
    paddingTop: 1,
    borderWidth: 1,
    width: responsiveWidth(41),
    height: responsiveHeight(13),
    borderColor: Colors.A_DIFFERENT_BLUE,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopRightRadius: 20,
  },
  TextNoOfTasksInProgress: {
    marginTop: 10,
    paddingLeft: 20,
    color: Colors.WHITE,
    fontWeight: 'bold',
    fontSize: 30,
  },
  TextInProgress: {
    marginRight: 30,
    marginTop: 5,
    color: Colors.WHITE,
  },
  TaskWaitingForReviewParent: {
    backgroundColor: Colors.A_DIFFERENT_BLUE,
    marginTop: 15,
    borderWidth: 1,
    paddingLeft: 20,
    width: responsiveWidth(41),
    height: responsiveHeight(20),
    borderColor: Colors.A_DIFFERENT_BLUE,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopRightRadius: 20,
  },
  TextWaitingForReview: {
    marginTop: 10,

    color: Colors.WHITE,
  },
  TextNoOfTasksWaitingForReview: {
    marginTop: 20,
    paddingLeft: 40,
    color: Colors.WHITE,
    fontWeight: 'bold',
    fontSize: 30,
  },
});

export default styles;
